### ISSUE TITLE
window split support?

### ISSUE THREAD

**Issue by lucasjinreal** [contour-terminal/contour#1170]
window split support?

**Comment by Yaraslaut** [comment]
Hi @lucasjinreal,
We are planning to implements tabs in the future, see https://github.com/contour-terminal/contour/issues/90 you can subscribe to the issue to be updated.

**Comment by uspasojevic96** [comment]
@Yaraslaut he meant this: https://github.com/lsd-rs/lsd

**Comment by Yaraslaut** [comment]
I also use `exa` :) 
@lucasjinreal  check that you are using desired shell inside contour, you can change it inside `contour.yml` file

**Comment by christianparpart** [comment]
#90 is about tabs, right. and #91 is about split support (tiling terminal views).

Now, with QML PR being finally merged, both are doable and pretty high on the list to be done for this year.

You may want to subscribe to both. Since #90 is slightly easier to implement (design-wise), that might come slightly earlier than #91.

I am closing this ticket here, @lucasjinreal, since what you ask for, is basically #91. Please at least sub to this one to get notified when we're having it implemented. :)
