### ISSUE TITLE
Set color schemes from external tools

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/contour#1285]
add support of  https://github.com/Gogh-Co/Gogh  to configure terminal colors

**Comment by christianparpart** [comment]
I think, to make it easier for the user to quickly tweak the look, we should also provide some pre-installed colorschemes that are compatible with Contour.

We could get inspired by [Gogh](https://github.com/Gogh-Co/Gogh/tree/master/themes). While PR'ing into their repo to make it compatible with Contour would work, I think we should ourself come with a  smallish (decent) set of colorscheme variations already.

At least the most well known should be provided. Otherwise, as long as licence permits, we could create a conversion script that helps creating the initial set of pre-installed colorschemes.

Here's a list of my favourite colorschemes from the past:

- Monokai
- Onedark
- Onelight
- Gruvbox
- Solarized
- Base16 (variations)
- PaperColor

The other note is, that Contour supports way more color entries per color scheme than others. We'd need to fill these out manually to provide some good-looking default.

**Comment by Yaraslaut** [comment]
I added predefined color palettes in the contour, so now users can config it easier, thus i will close this one as complete
