### ISSUE TITLE
Mouse scrolling is not working on not-main profile.

### ISSUE THREAD

**Issue by kierun** [contour-terminal/contour#1424]
### Contour Terminal version

0.4.1

### Installer source

something else (please specify below)

### Operating System

Fedora Linux 39

### Architecture

x86-64

### Other Software

N.A.

### Steps to reproduce

1. Add this below the `main` profile:
```yaml
    large:
        terminal_size:
            columns: 120
```
2. Run `contour profile large`
3. In the new terminal, `cat` some long file.
4. Use the mouse to scroll up.

### Expected Behavior

I expect the same behaviour as per the `main` profile: the mouse scrolls up.

### Actual Behavior

The mouse does nothing: the view does not change.

### Additional notes

I am pretty sure I must have missed something, but I am really unsure what it is. So, either it is a bug or the documentation could be improved. Either way, I am happy to help.

**Comment by christianparpart** [comment]
Hey @kierun. Many thanks for your interest and bug report. I'm sorry to see you having troubles with Contour. We'll be trying to investigate on this as soon as possible.

Sorry for the inconveniences.

**Comment by kierun** [comment]
@christianparpart  Thank you. Anything you need, please ask. I am happy to help in any ways I can.

**Comment by christianparpart** [comment]
I just reproduced it with your above configuration. The reason why mouse scrolling is not working is, because there's no history limit set, and that's defaulting to `0`. Once you add a history limit, it'll all just work.

I know, that configuration loading/reloading is currently not perfect. We're aware of it, and first work in form of a pending PR is already ongoing.

Apart from that, I wonder what a sane default would be, probably not `0`, as in: no history limit, maybe. Maybe a conservative limit of 1000 to (more useful) 10000 would be a good default.

**Comment by Yaraslaut** [comment]
> I confirm that setting the `history` to a none-zero value works. That's perfect, thank you.

bug with default `history` limit is fixed, so you might just delete this part of profile
