### ISSUE TITLE
OSC-8 link storage(?) broken for links generated with aerc colorize

### ISSUE THREAD

**Issue by ferdinandyb** [contour-terminal/contour#1499]
### Contour Terminal version

Contour Terminal Emulator 0.4.4-master-521b1408

### Installer source

Github: source code cloned

### Operating System

Ubuntu 22.04

### Architecture

x86-64

### Other Software

[Colorize](https://git.sr.ht/~rjarry/aerc/tree/master/item/filters/colorize.c) filter from aerc filters. Probably shouldn't be hard to build, but if you tell me what logs to make I can paste that as well.

### Steps to reproduce

I was running the below script:

```
#!/bin/bash

for (( i = 0; i < 20; i++ )); do
  echo "http://example$i.com" | ~/.local/libexec/aerc/filters/colorize -8
  # printf '\033]8;;http://example%s.com\033\\This is a link %s\033]8;;\033\\\n' "$i" "$i"
done
```

but actually two different links are enough to reproduce. Contour will consistently open the link corresponding to first link that was output by colorize in the terminal. A subsequent osc-8 with the commented out printf will work fine, but any osc-8 output by colorize will forever open the same (first) link.

### Expected Behavior

The proper links are opened.

### Actual Behavior

Contour will consistently open the link corresponding to first link that was output by colorize in the terminal. A subsequent osc-8 with the commented out printf will work fine, but any osc-8 output by colorize will forever open the same (first) link.

**Comment by Yaraslaut** [comment]
We see this bug because colorize.c sets id for the url, some info about id you can find here: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
While initial intention is to use id only for `Hover underlining` we also use it to `open links`. When user opens a link, we search for it  by `id` inside internal url cache, and since `id` is the same for all of them only first link is exist in the cache. 

Possible solution is to ignore user specified `id` since we set it  anyway, and when we count it internally then everything will go smooth  
Maybe @christianparpart  has a better idea
