### ISSUE TITLE
Feedback and suggestions for color palette notifications

### ISSUE THREAD

**Issue by gpanders** [contour-terminal/contour#1659]
Hi!

I've recently implemented [support in Neovim](https://github.com/neovim/neovim/pull/31350) for [color palette notifications](https://github.com/contour-terminal/contour/blob/master/docs/vt-extensions/color-palette-update-notifications.md). Having implemented, I have some feedback and suggestions for ways it could be modified to help our use case.

We are using these notifications to detect when the background color of the terminal has changed. In Neovim's case, we don't care about the OS appearance (at least not right now), all we care about is the terminal's background color. When we receive one of these notifications we send an OSC 11 query to determine the terminal's background color and update the `'background'` option appropriately.

However, we end up receiving a lot of these notifications because Neovim changes or resets the cursor color frequently (the user can set the `'guicursor'` option which can modify the color and shape of the cursor based on the current mode). Every time this happens, we get a color palette update notification, we query the terminal's background color, and we update `'background'`. This causes a lot of unnecessary "noise", both in unneeded terminal I/O but also in user-facing `OptionSet` events everytime `'background'` is set (even if the option's value doesn't change).

## Suggestions

Since all we (Neovim) care about is the terminal's background color, it would be great to be able to have more granularity about _what_ changed in the DSR. I can think of two ways to do this:

1. When we enable mode 2031, allow the application to specify which events it's interested in. In Neovim's case, we would "register" only for terminal background color changes. Other applications may choose to be notified for foreground color changes, or OS appearance changes. The drawback here is that I don't think this is possible with DECSET, since it doesn't take parameters.

2. Include more parameters in the DSR response to indicate what actually has changed. The parameters would include e.g. `10` for a foreground color change, `11` for a background color change, `12` for a cursor color change, and perhaps `4` for a palette color change (to match the OSC sequences). So for instance, if the OS appearance changed to black and background color changed, the terminal would send `CSI ? 997 ; 1 ; 11 n`. With this approach, Neovim would know to only query for the background color when the terminal's background color changed.

Please let me know your thoughts. Thanks for spearheading this feature, a lot of our users are very excited about it.

**Comment by christianparpart** [comment]
Thank you @gpanders. I will try to aid here ASAP.

**Comment by christianparpart** [comment]
Hi @gpanders. I've been re-reading your discussion and this issue again.

I think what you face is, when changing the color palette while having unsolicited DSR enabled, you also get a DSR for the updates that were triggered through the VT stream itself.

We could question now if that actually makes sense. I was having the other point of view in mind, that is, if the terminal decides to change the color palette (e.g. because the user switches the profile or the OS has changed between dark/light mode, leading to a color scheme change in the terminal). For this you definitely want the DSR, but not for the case where you change the color palette via a VT sequence (because you know you're doing it).

Does this sound reasonable to you?

/cc @kovidgoyal, @mitchellh - because you both implemented it on the TE side.

**Comment by kovidgoyal** [comment]
kitty will send out a notification *only* when the background color is changed, not other colors, regardless of the source of the change.  So if an application has requested notification and it changes the background color it will get *one* notification about it. Even if it was the one that initiated the change. That is unavoidable as kitty has no way to know who sent it the change request. The application could suspend itslef for example ctrl-z in vim. Or run a child program that does it.

**Comment by christianparpart** [comment]
Makes sense to me. Thanks for the quick reply. I'll see what to add to the spec to make it more helpful for TUI implementers.

**Comment by christianparpart** [comment]
@gpanders I think we can safely close this here now, since you're tracking it on the ghostty's side already. Feel free to ping us in the future for any other concerns :)

**Comment by krobelus** [comment]
Apps like NeoVim ignore the CSI 997 payload because they query OSC 10/11 instead.
So both NeoVim and kitty respect overrides, which sounds correct to me.

> However this has the downside that applications that override the background via OSC 11 and friends no longer get notified when terminal configured colors change, because overridden colors take priority over configured colors.

I think that's fine.
Of course, when the override is removed (color stack popped to length zero), the terminal should enable notifications again,
and the app needs to compensate for the disabled notifications by querying the color theme again.
- if the override was removed by a child process of our app (like a shell or Vim) owned the terminal, that should already work because the app wants to query the color theme already, even if there are no overrides because the system theme might have changed 
- if the override was removed while our app owns the terminal, then the app probably already knows that it needs to query again.
  Of course, in practice, printing escape sequences from shell builtins (`printf ..`) is an exception but that's probably tolerable, and could possibly be fixed in the shell for all realistic cases, or worked around by running `/bin/printf` instead or follow up with `printf '\033[?996n`, whose response should be consumed by the shell.

NeoVim still uses the Contour protocol to subscribe to notifications.
This begs the question why we need the CSI 997 payload at all. I guess it saves scripts from having to guess the theme mode by computing the relative luminance. I don't know for whom this is helpful. Maybe we should remove the payload and point readers to OSC 10 / 11.
