### ISSUE TITLE
Create headless terminal backend bench test using termbench-pro.

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#335]
https://github.com/contour-terminal/termbench-pro

It's a library. It's headless.

Let's see if we can get other terminals to use [termbench-pro](https://github.com/contour-terminal/termbench-pro) for internal backend performance testing, too. WT? ;-)

**Comment by data-man** [comment]
Great!
Currently I'm using https://github.com/cmuratori/termbench/tree/v3_work.
Unfortunately, it often breaks Contour. :(

**Comment by christianparpart** [comment]
> Great!
> Currently I'm using https://github.com/cmuratori/termbench/tree/v3_work.
> Unfortunately, it often breaks Contour. :(

Perfect! So let's fix it! (I know it's breaking on binary output at least, yeah).

I did this, so the benchmarking can be done 100% decoupled from the rendering, to *just* concentrate on the backend throughput but also be able to easier debug and get more determinism into it.

**Comment by WSLUser** [comment]
You'll probably be interested in https://github.com/microsoft/terminal/issues/10362. They've done alot of work and still continuing more as time permits to satisfy termbench for VT processing.

**Comment by christianparpart** [comment]
> You'll probably be interested in [microsoft/terminal#10362](https://github.com/microsoft/terminal/issues/10362). They've done alot of work and still continuing more as time permits to satisfy termbench for VT processing.

You will *never* *ever* satisfy what cmuratori claims. The values he claims are made up and based on a fundamental design flaw in refterm's buffer management. refterm is basically benchmarking `memcpy()`. Congratulations to that. :-)

I am aware of that ticket, but sadly I cannot comment there as I'm not a Windows Terminal contributor, even though I'd like to stay constructive. :)

**Comment by WSLUser** [comment]
Yeah I think the big thing is looking at hot spots in Process Explorer regarding VT processing and making improvements when able. It should satisfy termbench a bit more than before. As you might of noted in that issue, they already had compared to what was shown at first since it was based on an older conhost. Keep in mind that any conhost changes will also very likely help Contour as well since it's the backend behind ConPTY, which Contour uses.

**Comment by WSLUser** [comment]
https://github.com/microsoft/terminal/issues/10563 is MS's actual official issue for it, without any of the other stuff.

**Comment by skyline75489** [comment]
Hi guys. Really happy to see fantastic work is done here for Windows users to have another terminal to use. I would like to point out my issue is NOT anything official. Feel free to comment or anything, but I am only an outside contributor, who happens to work for MS.

**Comment by skyline75489** [comment]
> The values he claims are made up and based on a fundamental design flaw in refterm's buffer management

Yeah this is one of the reasons why refterm is fast. The buffer implementation benefits the `buffer -> renderer` side. Another reason is that refterm isn't really trying to be a terminal. It uses something close to raw IO (NamedPipe on Windows) instead of pty interface that the OS provides. This benefits hugely on the `program stdio -> buffer` side. As a result, refterm is not only faster than every terminal on Windows, it also beats the crap out of every single terminal on Linux & macOS (search twitter and you'll find the evidence).

In conclusion, refterm basically sets a standard that no real terminal can meet, if you're talking about a functional terminal. Sadly a lot of people out there treat refterm as something very close to a real terminal, and cmuratori does not seem to want to clarify the difference.

Also fun fact: all of the members of the terminal team (including me, an unofficial member) are blocked by cmuratori personally on both Github & Twitter. We can't comment, fork or even star the refterm repo (and all his other repos). That being said, I doubt any of us would really bother to poke him anymore, even if we're not blocked. Because that turned into something pretty irrational and emotional before, and I think no one wants one more time of that.

**Comment by christianparpart** [comment]
Closing as we have that on master now.
