### ISSUE TITLE
DECSET escape sequences

### ISSUE THREAD

**Issue by mintty** [contour-terminal/contour#558]
In descriptions (project page, control sequences) please replace DECSM/DECRM with DECSET/DECRST.
The variations without "?" are called SM (not DECSM) and RM.

**Comment by christianparpart** [comment]
Hey @mintty . Sure thing. I even personally prefer that. If I remember correctly, I was simply taking over these words from other places. I will gladly change that.

Happy remaining Christmas (holi)days. ;)

**Comment by j4james** [comment]
FYI, DEC always just refers to these controls as `SM` and `RM`, since a private parameter prefix shouldn't change the command - only the meaning of the parameter values. They refer to the ?-prefixed parameters as "DEC private modes", and the standard parameters as "ANSI modes". ECMA-48 documents private modes the same way.

So if you wanted to give the private sequences a unique name, I personally think `DECSM` and `DECRM` makes way more sense than `DECSET` and `DECRST`, but neither of those terms were officially used by DEC as far as I know. That said, I think `DECSET` and `DECRST` are probably how they're best known nowadays, just because that's what XTerm calls them.

Anyway, that's just a bit of historical trivia - not arguing for any particular choice of name. Call them whatever you like. 😃

**Comment by mintty** [comment]
I agree, thanks for the clarification. I was indeed referring to the xterm terminology. However, DECSM and DECRM are not in use anywhere else.
