### ISSUE TITLE
segfault with with latest git

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#600]
### Contour Terminal version

latest git

### Installer source

Github: source code cloned

### Operating System

arch linux

### Architecture

x86-64

### Other Software

none

### Steps to reproduce

build 
remove config 
start 

### Expected Behavior

contour starting

### Actual Behavior

segment fault

### Additional notes

https://termbin.com/m7r4
happens also with with stable

**Comment by uspasojevic96** [comment]
Question, what GPU do you have, or rather what OpenGL version it supports?

**Comment by data-man** [comment]
Compiled with Qt6, interesting...
Please, try with Qt5.

**Comment by uspasojevic96** [comment]
Possible, but he said that he tried the stable release also, which suggests something with GPU, look at the stacktrace, it's at rendering

**Comment by christianparpart** [comment]
```
terminal::renderer::Renderer::configureTextureAtlas
```

This suggests indeed that you are using the master branch, because that's one of the major changes for the next big release (0.3.0). This however does not exist in latest stable though. I think with "latest stable" you have been referring to how you are installing via AUR, which (AFAIR?) should also pick up from master branch. 

Judging from the provided stack trace (which sadly does not have line numbers ;-( ) it's even during startup. I am super sorry about this and I'll try to digg down into it soon.

Am I right to assume that it was once already working for you and it just started to fail since time X ?

**Comment by Glog78** [comment]
nope it's not master see -> https://termbin.com/fme6
https://i.imgur.com/kv8moQU.png

**Comment by Glog78** [comment]
as far as i can see ... the key part for the problem is not qt or the rendering ... for all the info i have an nvidia card and it works like a charm rendering opengl.
it might be a error with the config creation or first time setup ?!

![image](https://user-images.githubusercontent.com/7598856/152665337-81fe247e-a7f8-4e90-a66e-59e3a5c33784.png)
^^ shortly before i run over the bug i had / (still have) this strange spacing issue with the font. (it all worked before)

so i thought it might be good to start with a new  config and moved my old config into a backup.

I can say for sure !!
rm -rf ~/.config/contour << both contour stable and contour contour master segfault 
using the old config << both seem to start but have currently a rendering bug

my guess is the rendering bug is and issue with an very up to date maybe even buggy arch package (could be qt5-base, but my guess currently is more fontconfig)
i currently can't exclude my config cause as you can see ... it segfaults when i try to do

**Comment by christianparpart** [comment]
Guten Morgen!

Many thanks for thy patience. Those is indeed interesting. The referring changed inherently between last release and master branch. I will see where I am missing some error checks somewhat in a free spot today.

Greetings from gray Berlin.

**Comment by christianparpart** [comment]
Ah, can I get you into Discord for a more direct investigation in

**Comment by christianparpart** [comment]
I'm trying to look into this right now. Do you have minimal experience in using GDB? Did you build from master by yourself? If so, would you mind doing the following for me?

* build the project in debug mode, e.g. by invoking this: `cmake -DCMAKE_BUILD_TYPE=Debug build/` (assuming your in project root and your build dir is called "build").
* then, when having built, run contour inside gdb. e.g. via `gdb ./build/src/contour/contour`
* inside gdb, type `r` to start running. wait for the crash
* when it happened, you can type in `bt` or `bt full`.

That one you can paste in here, literally, embedded into `<details>`. My goal is to see the line numbers. I'm asking because there isn't really much happening in the `configureTextureAtlas()` and yet your stacktrace shows it is crashing in that function (but not where).

Thanks for your patience,
Christian.

**Comment by christianparpart** [comment]
There might be a division-by-zero hidden in your SEGV. You might want to try out the above branch from the PR. It will not fix it but give more insights at least. :)

**Comment by Glog78** [comment]
[gdb.bt.log](https://github.com/contour-terminal/contour/files/8010598/gdb.bt.log)

is this enough or do you still want me to test the branch from the PR ?

**Comment by Glog78** [comment]
[contour.log](https://github.com/contour-terminal/contour/files/8010635/contour.log)
[gdb.bt.log](https://github.com/contour-terminal/contour/files/8010636/gdb.bt.log)

fix/bug-600 branch used

**Comment by christianparpart** [comment]
@Glog78 okay, that was quick and definitely helpful. Your tile-size is zero. That's why it aborts right in the beginning. I'll keep you posted.

**Comment by Glog78** [comment]
fun fact it doesn't become zero if i have my old config 
but something did change the font behaivior

i had strict_spacing off for all the time and it did render everything just fine ... since yesterday i need strict_spacing to be on so i don't get completly screwed spacing. I guess thats not your fault but rather some changes comming with arch.

So the tile-size being zero can also be because some font or fontconfig being "different" than before ?
I didn't not dig deeper , somehow i can use an embedded fontconfig ... maybe that would fix the crash but i would need to change the full arch package description cause i need submodules to be checked out.... a whole different beast to do

**Comment by christianparpart** [comment]
@Glog78 I've pushed to that investigation branch again.

Would you please mind updating & rebuilding and then run contour with the following parameters?

```
./build/src/contour/contour debug "vt.renderer,gui.*,font.*"
```

Now you should be getting a rather spammy output when starting up, with however some useful insights on what fonts are found, and loaded in which order and how your **average glyph width** is calculated. Because that is what is zero in the end.

Also, would you mind trying a different font?

> fun fact it doesn't become zero if i have my old config but something did change the font behavior

Meaning, that in your old config you had a custom set font (which) and the new one is the default config, which is using `monospace` as key. Do you have any custom tweaks to your fontconfig (either in /etc/fontconfig or in ~/.fontconfig (or so))? If so, maybe the meaning of "monospace" has changed to something interesting.

> i had strict_spacing off for all the time and it did render everything just fine ... since yesterday i need strict_spacing to be on so i don't get completly screwed spacing. I guess thats not your fault but rather some changes coming with arch.

It is some time ago I last touched the way font loading works. But at least we know your problem isn't related to any of the prior thought ones (Qt, OpenGL, GPU).

So the tile-size being zero can also be because some font or fontconfig being "different" than before ?
I didn't dig deeper , somehow i can use an embedded fontconfig ... maybe that would fix the crash

Please don't go that route. Embedding packages is indeed supported for most primary dependencies, but only recommended when the system doesn't provide that package or does not meet the version requirements.

but i would need to change the full arch package description cause i need submodules to be checked out.... a whole different beast to do

We don't do submodules anymore. We have a long history of how to deal with dependencies (starting with submodules if I remember correctly :-D )

So while waiting for some really interesting insights from the command above (being executed by you), I'll still try to find a graceful way to work around such cases.

**Comment by christianparpart** [comment]
> Sorry for the late response i was busy today

I'm having family and duties 24/7 myself. I don't expect anyone to be **that** responsive. So, whatever time/-frame works best for you.

> is this enough or do you still want me to test the branch from the PR ?

Now again, yes, sorry. :)

**Comment by Glog78** [comment]
[contour.log](https://github.com/contour-terminal/contour/files/8011047/contour.log) << the requested log

**Comment by christianparpart** [comment]
Your first font being found on top of everything else is "Powerline". This sounds like a custom configuration, is it? Judging from the path it looks like a system-installed font, but why is the `Powerline.otf` priority above all?

NB: I'm still trying to code a workaround such that others won't run into this in the future.

**Comment by Glog78** [comment]
[contour.log](https://github.com/contour-terminal/contour/files/8011108/contour.log)

it's not a personal config as you can see in the above log

**Comment by christianparpart** [comment]
@Glog78 It seems (as per your log file) that you do require "strict spacing". Your NotoSansMono-Regular.ttf though does not expose that spacing attribute, so it's skipped and the next one is your Powerline font file, which does not contain any US-ASCII glyphs, and that is why the average glyph width is zero.

With the new commit I just pushed such font files are not skipped anymore and you should be just fine.

Would you mind giving it a try, please?

**Comment by Glog78** [comment]
fixed it ... thank you alot

**Comment by christianparpart** [comment]
> fixed it ... thank you alot

Ditto!
