### ISSUE TITLE
Procedure entry point createPseudoConsole was not found in the dll

### ISSUE THREAD

**Issue by Medel** [contour-terminal/contour#657]
### Contour Terminal version

0.3.0.198

### Installer source

GitHub: release page

### Operating System

Win 10 version 1703 Build 15063.483

### Architecture

x86-64

### Steps to reproduce

Program from release page: contour-0.3.0.198-win64.msi

If I start contour.exe I get an error:
Procedure entry point createPseudoConsole was not found in the dll "C:\Program File\Contour 0.2.3.183\bin\contour.exe

Same with: contour-0.3.0.198-win64.zip

### Expected Behavior

Program start

### Actual Behavior

The error messages appears

**Comment by uspasojevic96** [comment]
That Windows is from 2017, can you try updating your Windows 10?

**Comment by christianparpart** [comment]
A fallback could be implemented using the wide spread [winpty](https://github.com/rprichard/winpty) bridge. Not sure that would give us anything that we don't have when using ConPTY (image graphics? :-D).

So for backwards compatibility with older Windows OS's, I don't see myself adding winpty support (simply due to time constraints), but if someone would jump in and create a PR for adding winpty support, I'd be more than happy to accept that.

Until then, @Medel , I think the only option for you would be to update your Windows to at least build number 18309 (Windows 10 version 1803).

**Comment by Yaraslaut** [comment]
I close it since we will not fix it
