### ISSUE TITLE
Rendering gdb tui mode seems broken

### ISSUE THREAD

**Issue by herrhotzenplotz** [contour-terminal/contour#661]
I guess this one is pretty obvious:

![2022-04-30-120827_998x632_scrot](https://user-images.githubusercontent.com/34663024/166101269-767e7391-6ff7-45d6-88fb-fef1b0f41a3b.png)

Steps to reproduce:

```console
$ gdb -q -tui --args ./foobar
```

**Comment by christianparpart** [comment]
I in fact had to check how it is supposed to look like.

There are two problems to be fixed:

- [ ] box-drawing not showing the expected characters (maybe due to shift-select VT sequences?)
- [ ] background color should have been cleared, but isn't?

That's urgent enough, IMHO, i'll fix that right after i'm done with selection PR.

**Comment by whisperity** [comment]
Affects more than just `gdb tui`. `aptitude`:

![Screenshot_20220502_161829](https://user-images.githubusercontent.com/1969470/166249703-8970f0bb-71ac-4cae-8a46-5053a6c64fe5.png)

**Comment by christianparpart** [comment]
All fixed on `master`.
