### ISSUE TITLE
Can't use Ctrl-C (SIGINT) when there is text selection

### ISSUE THREAD

**Issue by uspasojevic96** [contour-terminal/contour#683]
### Contour Terminal version

Contour Terminal Emulator 0.3.2-unreleased-master-7f3454b6

### Installer source

Github: source code cloned

### Operating System

Gentoo

### Architecture

x86-64

### Steps to reproduce

- Start contour
- Select any text
- Press Ctrl-C

### Expected Behavior

To send Ctrl-C

### Actual Behavior

Nothing

**Comment by christianparpart** [comment]
Thanks, I just verified it, it's happening to me to, but then I looked into my config.

Do you have Ctrl+C bound to CopySelection maybe iff something is selected?

We should probably overhaul the default key binds :)

**Comment by uspasojevic96** [comment]
Ctrl-Shift-C is my copy binding

**Comment by christianparpart** [comment]
Do you maybe have more than one line in the config for `CopySelection` action? probably still left over from the initial default config?

the `Select` mode simply means something is selected, that's not the new vi-like input modes, there we only expose ViNormalMode for now.

**Comment by uspasojevic96** [comment]
`- { mods: [Control],        key: C,             action: CopySelection, mode: 'Select' }`
have this as additional `CopySelection` but still, this is redundant, since we already have `Ctrl-Shift-C` as `CopySelection` it's implied that it is being done on selection

**Comment by christianparpart** [comment]
You press Ctrl+C while having something selected. You have two lines in the key mappings, one for Ctrl+Shift+C and one for Ctrl+C and that latter one at least with mode set to Select. Since you have something selected, this line matches and the action gets executed (copying the selection). That does not implicitly deselect. But since it performed an action, Ctrl+C is not going to be forwarded to the application.

I think we should either remove that line from the default config, or make it more obvious what's happening (i.e. cancelling the selection after copying).

**Comment by Yaraslaut** [comment]
Bug is not happening anymore after configuration file changes, thus closing
