### ISSUE TITLE
Trying to go past the right side of window in vim mode crashes.

### ISSUE THREAD

**Issue by Utkarsh-khambra** [contour-terminal/contour#917]
### Contour Terminal version

Contour Terminal Emulator 0.3.8-master-5097e75c

### Installer source

Github: source code cloned

### Operating System

Fedora 37

### Architecture

x86-64

### Steps to reproduce

1. Switch to vim mode.
2. Go to right side of window and press L a bunch of times.

### Expected Behavior

Cursor should stay on the right side

### Actual Behavior

Contour crashes  with this 
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 80) >= this->size() (which is 80)
```

**Comment by christianparpart** [comment]
I can fix that asap. Thanks. :)

**Comment by elmarsan** [comment]
Hello.  
I'm experimenting the same issue.  (Using vi and nvim)
[vim-exit.webm](https://github.com/contour-terminal/contour/assets/43180519/fe8b61b5-e2e4-478b-bc1a-0cd95c998998)

**Comment by Yaraslaut** [comment]
> 

Hello,
Thanks for the report,  i think it might be connected with terminfo file and TERM variable, check this part of documentation : http://contour-terminal.org/install/?h=terminfo#installing-from-source 
you need to ensure that contour can set TERM=contour on startup, you can check if `echo $TERM` gives you `contour` and not something like `xterm`, locally I can not reproduce results from your video.
If it does not solve this issues or you are having problems settings things up please open new issue, since this one contains description of the crash.
