### ISSUE TITLE
contour exits immediately after running it

### ISSUE THREAD

**Issue by anakimluke** [contour-terminal/contour#987]
### Contour Terminal version

0.3.10-master-634603d3 and tag v0.3.9.250 and latest github appimage release and flatpak

### Installer source

Github: source code cloned

### Operating System

Debian 11

### Architecture

x86-64

### Other Software

Tested on xfce 4.16

### Steps to reproduce

Run contour.

### Expected Behavior

Expected contour window to pop up.

### When trying to run from a freshly built binary(from master,634603d)

A window pops up and very quickly closes, then the process terminates with the following error:

```
libpng warning: iCCP: known incorrect sRGB profile
[error] freetype: Failed to set LCD filter. unimplemented feature
fish: “contour” terminated by signal SIGILL (Illegal instruction)
```

When running as root there's a slightly different error message:

```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
PulseAudioService: pa_context_connect() failed
[error] Default output device doesn't support 16 Bit signed integer PCM
[error] freetype: Failed to set LCD filter. unimplemented feature
fish: “sudo contour” terminated by signal SIGILL (Illegal instruction)
```
### When trying to run from a freshly built binary(from the latest tag I found, v0.3.9.250):

The quickly disappearing window is also present here, and when ran as root.

```
[error] Superfluous config key found: profiles.main.mouse.hide_while_typing
[error] Superfluous config key found: profiles.main.mouse
libpng warning: iCCP: known incorrect sRGB profile
[error] freetype: Failed to set LCD filter. unimplemented feature
fish: “contour” terminated by signal SIGILL (Illegal instruction)
```
And running as root:
```
[error] Superfluous config key found: profiles.main.mouse.hide_while_typing
[error] Superfluous config key found: profiles.main.mouse
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
PulseAudioService: pa_context_connect() failed
[error] Default output device doesn't support 16 Bit signed integer PCM
[error] freetype: Failed to set LCD filter. unimplemented feature
fish: “sudo contour” terminated by signal SIGILL (Illegal instruction)
```

### When trying to run via flatpak:

A window quickly opens up and closes down.

```
Gtk-Message: 23:00:24.921: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
libpng warning: iCCP: known incorrect sRGB profile
[error] freetype: Failed to set LCD filter. unimplemented feature
```

### When trying to run via appimage:

In contrast with running a home brewed binary and flatpak, running the appimage does not result in a window quickly opening up and then closing down.
```
[error] Superfluous config key found: profiles.main.mouse.hide_while_typing
[error] Superfluous config key found: profiles.main.mouse
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
fish: “./contour-0.3.9.250.x86_64.AppI…” terminated by signal SIGABRT (Abort)
```

### Additional notes

Commands like `contour version` and `contour help` seem to work normally.

**Comment by christianparpart** [comment]
Good morning @anakimluke. 
That's interesting and weird at the same time.

## AppImage

The official AppImage is reported to have issues on some platforms. We're aware of it and there's actually one upstream bug (at appimage builder side) that needs fixing before we can finish fixing on our side. I should probably remove it from the release set until then. :)

> This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

THIS is the one to look out fore. Qt works on a variety of platforms. It seems to be unable to find an appropriate plugin. Are you on Wayland or on X11? It tries to load the "xcb" (X11) plugin but apparently no plugins are available. This is a packaging error on the tool we use to package contour for AppImage. It's reported upstream but (last time I checked) no fix yet. I'll update this ticket I guess when done (we also have a tracking ticket [here](https://github.com/contour-terminal/contour/issues/832)).

### Flatpak

I think you could have tested that one only through [flathub](https://beta.flathub.org/apps/details/org.contourterminal.Contour), right? That's weird, because this is certainly better sandboxed than AppImage and it should work (at least on my tests and no other complaints so far). 🤔 

> Gtk-Message: 23:00:24.921: Failed to load module "xapp-gtk3-module"

this seems to be some desktop-thing. I've never seen that (so far).

> Qt: Session management error: Could not open network socket

Never noticed that, but I can imagine that this is surely fixable (if needed) to get session management working. We want to improve on session restauration in the future anyways.

> libpng warning: iCCP: known incorrect sRGB profile

Qt is using libpng for dealing with .png image files. Seems like some PNG files on your installation have a bad PNG header. This warning can apparently be ignored because libpng can deal with it. There's a good thread about [here](https://stackoverflow.com/a/22747902/386670).

> [error] freetype: Failed to set LCD filter. unimplemented feature

You must have a stripped down version of freetype that doesn't support LCD subpixel rendering. It's not the first time I am seeing that. But I don't think that should stop you from using Contour.

On Flatpak, there are some steps required to get OpenGL accelerated apps running:

```sh
christianparpart@fedora-arm64-vm ~> flatpak list | grep -w GL
Mesaorg.freedesktop.Platform.GL.default           21.3.9      21.08    system
```

You **might** be able to work around this by setting `renderer.backend` to `software` in `~/.var/app/org.contourterminal.Contour/config/contour/contour.yml` (this is the config file used when running through Flatpak, otherwise it's in `~/.config/contour/contour.yml`).

## Freshly built binary from master

> fish: “contour” terminated by signal SIGILL (Illegal instruction)

This is mind bogging. Okay, You say you're on an x86-64. Can you please paste the output of `lscpu` here?
Because Contour is (as of today) *still* using some advanced CPU instructions to speed up cache management, namely AES-NI. If you CPU doesn't have it, that might be the only reason that I can think of why ALL of your attempts failed.

We have a related tracker here: #741

I might be curious to see if that's the reason.

**Comment by anakimluke** [comment]
My CPU does not support AES-NI. I tested the flatpak on a CPU that does and it did work.

**Comment by christianparpart** [comment]
Okay, many thanks @anakimluke. I'm sorry for the inconveniences. We'll be working on non supporting hardware that doesn't provide crypto instructions ASAP. :)
